# Inputs for the AWS column of docs/architecture/components/10 §1. Every value a human must supply is in
# envs/aws.tfvars.example; everything else has a demo-sized default.

# --- naming and placement -------------------------------------------------------------------------------------

variable "region" {
  description = "AWS region for everything except the CloudFront WAF (always us-east-1). Must offer Bedrock AgentCore."
  type        = string
  default     = "us-east-1"
}

variable "name_prefix" {
  description = "Short project prefix for resource names."
  type        = string
  default     = "att"

  validation {
    condition     = can(regex("^[a-z][a-z0-9]{1,9}$", var.name_prefix))
    error_message = "name_prefix: 2-10 lowercase letters/digits, starting with a letter."
  }
}

variable "environment" {
  description = "Environment name, part of every resource name (dev, demo, ...)."
  type        = string
  default     = "dev"

  validation {
    condition     = can(regex("^[a-z][a-z0-9]{1,9}$", var.environment))
    error_message = "environment: 2-10 lowercase letters/digits, starting with a letter."
  }
}

variable "tags" {
  description = "Extra tags on every resource."
  type        = map(string)
  default     = {}
}

variable "image_tag" {
  description = "Image tag pushed by `make push` (the git sha). All five services use the same tag."
  type        = string
  default     = "latest"
}

variable "log_retention_days" {
  description = "CloudWatch log retention for every log group this stack creates."
  type        = number
  default     = 14
}

# --- data -----------------------------------------------------------------------------------------------------

variable "dynamodb_tables" {
  description = <<-EOT
    The seven DynamoDB tables as data. Do not edit by hand: `tables.auto.tfvars.json` is generated by
    `uv run python deploy/terraform/modules/dynamodb/generate.py` from tower_consent.tables and
    alerts.state.terraform_definition(), and a test fails when it is stale.
  EOT
  type = map(object({
    name         = string
    billing_mode = string
    hash_key     = string
    range_key    = optional(string)
    attributes   = list(object({ name = string, type = string }))
    global_secondary_indexes = list(object({
      name            = string
      hash_key        = string
      range_key       = optional(string)
      projection_type = string
    }))
    ttl                    = object({ enabled = bool, attribute_name = string })
    point_in_time_recovery = bool
  }))
}

# --- network ----------------------------------------------------------------------------------------------------

variable "vpc_cidr" {
  description = "CIDR of the VPC holding the mock carrier (Fargate + internal ALB)."
  type        = string
  default     = "10.42.0.0/16"
}

variable "az_count" {
  description = "Availability zones to span (an ALB needs two)."
  type        = number
  default     = 2
}

variable "enable_nat_gateway" {
  description = <<-EOT
    One NAT gateway for the private subnets. Off by default (about $32/month, more than the rest of the demo):
    Fargate tasks run in public subnets with a public IP and a security group that admits only the ALB. Turn it
    on for the cut-line configuration (tower_carrier_client = "direct"), where AgentCore Runtime runs in the VPC.
  EOT
  type        = bool
  default     = false
}

# --- carrier (mock or sandbox — a config swap the gateway cannot see) -----------------------------------------

variable "carrier_backend" {
  description = "mock | sandbox. Recorded in CARRIER_BACKEND; the code never branches on it (rule 6)."
  type        = string
  default     = "mock"

  validation {
    condition     = contains(["mock", "sandbox"], var.carrier_backend)
    error_message = "carrier_backend must be mock or sandbox."
  }
}

variable "tower_carrier_client" {
  description = <<-EOT
    gateway: Tower -> AgentCore Gateway (+ Identity) -> carrier (the target shape).
    direct:  the cut-line configuration of prompts/00 — Tower's DirectClient -> the mock's internal ALB, Runtime
             in the VPC (needs enable_nat_gateway = true), no Gateway or Identity resources are used by Tower.
  EOT
  type        = string
  default     = "gateway"

  validation {
    condition     = contains(["gateway", "direct"], var.tower_carrier_client)
    error_message = "tower_carrier_client must be gateway or direct."
  }
}

variable "binding_carrier_client" {
  description = <<-EOT
    How the binding page runs Number Verification's auth-code exchange. gateway (default, 05 §3): the
    number-verification Gateway target with an AUTHORIZATION_CODE Identity provider. direct: the binding page's
    own DirectClient, for when the Gateway auth-code path does not fit the carrier (the CIBA precedent in 05 §3).
  EOT
  type        = string
  default     = "gateway"

  validation {
    condition     = contains(["gateway", "direct"], var.binding_carrier_client)
    error_message = "binding_carrier_client must be gateway or direct."
  }
}

variable "carrier_target_scopes" {
  description = <<-EOT
    OAuth scopes Identity requests per Gateway target (API name -> scopes). Default: the coarse scope named after
    the API, which the mock's registry grants (a granted scope covers "<scope>:..."). A sandbox may need the
    fine-grained scopes from each spec's `security` block instead.
  EOT
  type        = map(list(string))
  default     = {}
}

variable "sandbox_base_url" {
  description = "Sandbox apiRoot (https://...). Used only when carrier_backend = sandbox."
  type        = string
  default     = ""
}

variable "sandbox_issuer" {
  description = "Sandbox OAuth issuer. Used only when carrier_backend = sandbox."
  type        = string
  default     = ""
}

variable "sandbox_token_url" {
  description = "Sandbox OAuth token endpoint. Used only when carrier_backend = sandbox."
  type        = string
  default     = ""
}

variable "sandbox_authorize_url" {
  description = "Sandbox OAuth authorize endpoint (Number Verification). Used only when carrier_backend = sandbox."
  type        = string
  default     = ""
}

variable "sandbox_client_id" {
  description = "Sandbox client id for service-level APIs (handed to AgentCore Identity, nowhere else)."
  type        = string
  default     = ""
}

variable "sandbox_client_secret" {
  description = "Sandbox client secret (handed to AgentCore Identity). Set via TF_VAR_sandbox_client_secret, never in a file."
  type        = string
  default     = ""
  sensitive   = true
}

variable "sandbox_binding_client_id" {
  description = "Sandbox client id for Number Verification (auth code)."
  type        = string
  default     = ""
}

variable "sandbox_binding_client_secret" {
  description = "Sandbox client secret for Number Verification. Set via TF_VAR_..., never in a file."
  type        = string
  default     = ""
  sensitive   = true
}

# --- mock carrier on Fargate ----------------------------------------------------------------------------------

variable "mock_domain_name" {
  description = <<-EOT
    Hostname for the mock carrier's internal ALB (e.g. mock.carrier.example.org). Gateway and Identity call it
    over HTTPS, so it needs a certificate: either give mock_route53_zone_id (a public zone you own — ACM validates
    by DNS and the record resolves to the internal ALB's private IPs) or an existing mock_certificate_arn.
  EOT
  type        = string
  default     = ""
}

variable "mock_route53_zone_id" {
  description = "Public Route 53 zone for mock_domain_name: creates the ACM certificate and the alias record."
  type        = string
  default     = ""
}

variable "mock_certificate_arn" {
  description = "Existing ACM certificate for mock_domain_name (instead of mock_route53_zone_id)."
  type        = string
  default     = ""
}

variable "mock_scenario" {
  description = "Scenario the mock loads at start (scenarios/<name>.yaml baked into the image)."
  type        = string
  default     = "demo"
}

# --- Tower on AgentCore Runtime -----------------------------------------------------------------------------------

variable "tower_jwt_discovery_url" {
  description = <<-EOT
    OIDC discovery URL of the identity provider that issues the Alexa+ / reference-client bearer (spike A:
    bearer JWT, user_id = sub). Empty = Runtime's default IAM (SigV4) inbound auth, for the reference client only.
  EOT
  type        = string
  default     = ""
}

variable "tower_jwt_allowed_audience" {
  description = "Allowed `aud` values for the inbound JWT."
  type        = list(string)
  default     = []
}

variable "tower_jwt_allowed_clients" {
  description = "Allowed `client_id` values for the inbound JWT."
  type        = list(string)
  default     = []
}

variable "tower_jwks_url" {
  description = "TOWER_JWKS_URL: Tower verifies the bearer itself as well (defence in depth; 01 §4)."
  type        = string
  default     = ""
}

variable "tower_jwt_issuer" {
  description = "TOWER_JWT_ISSUER."
  type        = string
  default     = ""
}

variable "tower_timezone" {
  description = "TOWER_TZ: default line-holder timezone."
  type        = string
  default     = "America/Toronto"
}

variable "enable_ref_client_runtime" {
  description = "Also host the reference client as a second Runtime agent (the Strands-on-Bedrock showcase)."
  type        = bool
  default     = false
}

variable "bedrock_model_id" {
  description = "BEDROCK_MODEL_ID for the optional reference-client runtime."
  type        = string
  default     = "amazon.nova-micro-v1:0"
}

# --- alerts, SMS, schedules ---------------------------------------------------------------------------------------

variable "alerts_timezone" {
  description = "Timezone of the daily 08:00 polls (10 §3 says local time by line; one zone at demo scale)."
  type        = string
  default     = "America/Toronto"
}

variable "sms_sandbox_numbers" {
  description = <<-EOT
    E.164 demo phones to register in the SNS SMS sandbox. Not applied by Terraform (registration needs the OTP
    sent to the phone); the output `sms_sandbox_commands` prints the two CLI calls per number. Keep this list in
    your untracked tfvars only.
  EOT
  type        = list(string)
  default     = []
  sensitive   = true
}

variable "sms_monthly_spend_limit" {
  description = "SNS SMS monthly spend cap in USD (the account default is 1)."
  type        = number
  default     = 1
}

variable "enable_push_topic" {
  description = "Create the optional push-notification SNS topic (06 §3)."
  type        = bool
  default     = false
}

# --- edge ---------------------------------------------------------------------------------------------------------

variable "enable_cloudfront_waf" {
  description = <<-EOT
    Put CloudFront + a WAF web ACL in front of the HTTP API (10 §1 "Lambda + API Gateway + CloudFront"; WAF
    cannot attach to an HTTP API directly). The rate rule applies to /hooks/*. Off = the raw API endpoint, with
    API Gateway route throttling on /hooks/* only.
  EOT
  type        = bool
  default     = true
}

variable "hooks_rate_limit" {
  description = "WAF rate limit: requests per 5 minutes per source IP on /hooks/* (minimum 100)."
  type        = number
  default     = 300
}
