# The seven tables, from data (04 §4, 06 §7, 10 §2). `tables` is var.dynamodb_tables at the root, which comes
# from tables.auto.tfvars.json, generated by generate.py in this folder from the Python definitions
# (tower_consent.tables + alerts.state). Hand edits to that file are overwritten and caught by a test.

resource "aws_dynamodb_table" "this" {
  for_each = var.tables

  name         = "${var.prefix}${each.key}"
  billing_mode = each.value.billing_mode
  hash_key     = each.value.hash_key
  range_key    = each.value.range_key

  dynamic "attribute" {
    for_each = each.value.attributes
    content {
      name = attribute.value.name
      type = attribute.value.type
    }
  }

  dynamic "global_secondary_index" {
    for_each = each.value.global_secondary_indexes
    content {
      name            = global_secondary_index.value.name
      hash_key        = global_secondary_index.value.hash_key
      range_key       = global_secondary_index.value.range_key
      projection_type = global_secondary_index.value.projection_type
    }
  }

  dynamic "ttl" {
    for_each = each.value.ttl.enabled ? [each.value.ttl] : []
    content {
      enabled        = true
      attribute_name = ttl.value.attribute_name
    }
  }

  point_in_time_recovery {
    enabled = each.value.point_in_time_recovery
  }

  server_side_encryption {
    enabled     = true
    kms_key_arn = var.kms_key_arn
  }

  deletion_protection_enabled = false # `make down` returns the account to zero
}
