# The one settings file: ./.env (gitignored; template .env.example). Every non-empty KEY=value is set here and
# exported to all recipes, before any default below, so it wins over the shell and the `?=` defaults; `make
# KEY=value` still wins over it. CRLF line endings are tolerated. A value with `$` or `#` would be expanded or
# cut by make, so it stops instead (line number only — never the value).
ROOT_ENV_FILE := .env
ifneq ($(wildcard $(ROOT_ENV_FILE)),)
ROOT_ENV_BAD := $(shell sed 's/\r$$//' $(ROOT_ENV_FILE) | grep -nE '^[A-Za-z_][A-Za-z0-9_]*=.*([$$]|\#)' | cut -d: -f1)
ifneq ($(ROOT_ENV_BAD),)
$(error $(ROOT_ENV_FILE) line(s) $(ROOT_ENV_BAD): `$$` and `#` are not allowed in values — see .env.example)
endif
define ROOT_ENV_NL


endef
ROOT_ENV_KEYS := $(shell sed -n 's/\r$$//; s/^\([A-Za-z_][A-Za-z0-9_]*\)=..*/\1/p' $(ROOT_ENV_FILE))
$(eval $(subst @@NL@@,$(ROOT_ENV_NL),$(shell sed -n 's/\r$$//; s/^\([A-Za-z_][A-Za-z0-9_]*\)=\(..*\)$$/\1 := \2@@NL@@/p' $(ROOT_ENV_FILE))))
export $(ROOT_ENV_KEYS)
endif

ENV ?= local
VALID_ENVS := local eks aws
ifeq ($(filter $(ENV),$(VALID_ENVS)),)
$(error ENV must be one of: $(VALID_ENVS) (got '$(ENV)'))
endif
UV ?= uv
PY := $(UV) run python
PYTEST := $(UV) run pytest
COMPOSE := docker compose -f deploy/compose/docker-compose.yml
COMPOSE_ENV_FILE := deploy/compose/.env
COMPOSE_LOGS := deploy/compose/logs
FORCE ?= 0
# Output toggles. Colour in `make help` only on a terminal; NO_COLOR=1 (https://no-color.org) or COLOR=0 turns it
# off. QUIET=1 silences make's own command echo and directory chatter (recipes still print their output).
COLOR ?= $(if $(NO_COLOR),0,$(shell [ -t 2 ] && echo 1 || echo 0))
ifeq ($(QUIET),1)
MAKEFLAGS += --silent --no-print-directory
endif
SERVICES := mock-carrier tower-mcp binding-page alerts ref-client
# Built locally, never pushed (doc 11 §8.7): `push` and ECR stay at SERVICES; build/sbom/scan cover IMAGES.
IMAGES := $(SERVICES) demo-ui
GIT_SHA := $(shell git rev-parse --short HEAD 2>/dev/null || echo dev)
# endpoints per ENV (local defaults; eks/aws are rendered from outputs by scripts/render_env.py)
ifeq ($(ENV),local)
TOWER_URL ?= http://localhost:8080/mcp
MOCK_URL ?= http://localhost:8443
BINDING_URL ?= http://localhost:8081
ALERTS_URL ?= http://localhost:8082
DYNAMO_ENDPOINT ?= http://localhost:8000
# Tower's local bearer lives in deploy/compose/.env (generated by `make up`); host-side tools (ref-client, the
# e2e tests) read it from there. Recursive, so it is read when a recipe runs, after `make up` has written it.
TOWER_BEARER ?= $(shell sed -n 's/^TOWER_BEARER=//p' $(COMPOSE_ENV_FILE) 2>/dev/null)
export TOWER_BEARER
# The mock's admin bearer (G1, 08 §3) for host-side tools: make demo, the e2e helpers, showcase-ui.
MOCK_ADMIN_TOKEN ?= $(shell sed -n 's/^MOCK_ADMIN_TOKEN=//p' $(COMPOSE_ENV_FILE) 2>/dev/null)
export MOCK_ADMIN_TOKEN
else
-include deploy/.env.$(ENV)
endif
export ENV TOWER_URL MOCK_URL BINDING_URL ALERTS_URL DYNAMO_ENDPOINT
# `require-env`: a prerequisite for targets that talk to a running eks/aws deployment. Locally it is a no-op;
# otherwise deploy/.env.$(ENV) (written by `make outputs` / `make deploy-eks` from terraform outputs) must exist.
.PHONY: require-env
require-env:
	@if [ "$(ENV)" != "local" ] && [ ! -f deploy/.env.$(ENV) ]; then \
	  echo "ENV=$(ENV): deploy/.env.$(ENV) not found — run $(if $(filter aws,$(ENV)),make outputs ENV=aws,make deploy-eks) first"; exit 2; fi
define not_built
	@echo "$(1): not built yet — see prompts/$(2)"
endef
