"""`ref-client corpus`: the tool-selection regression (09 §3). For every phrasing in `corpus/phrasings.yaml`,
ask the agent, compare the tool it chose (and the arguments) with the expectation, print a markdown table, write
`artifacts/corpus.md`, and fail below `CORPUS_MIN_PASS` (default 0.9).

A miss is a description bug, not a model bug: fix the words in `docs/architecture/components/01` §2 and
`tower_mcp/descriptions.py` together (08's drift test keeps them equal).
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any

import yaml

from ref_client.agent import Agent
from ref_client.transcript import Turn, normalise_args, redact

DEFAULT_MIN_PASS = 0.9
CLARIFY = re.compile(r"\b(which|whose)\b", re.I)


def corpus_path() -> Path:
    override = os.environ.get("REF_CORPUS")
    if override:
        return Path(override)
    packaged = resources.files("ref_client") / "_data" / "phrasings.yaml"
    if packaged.is_file():
        return Path(str(packaged))
    return Path(__file__).resolve().parents[2] / "corpus" / "phrasings.yaml"


def load_corpus(path: Path | None = None) -> list[dict[str, Any]]:
    data = yaml.safe_load((path or corpus_path()).read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("phrasings.yaml must be a list of entries")
    return data


def min_pass() -> float:
    return float(os.environ.get("CORPUS_MIN_PASS", DEFAULT_MIN_PASS))


def expectations(entry: dict[str, Any]) -> list[dict[str, Any]]:
    if "expect_any" in entry:
        return list(entry["expect_any"])
    return [entry["expect"]]


def describe(expect: dict[str, Any]) -> str:
    if expect.get("clarify"):
        return "clarify"
    if expect.get("tool") is None:
        return "no tool"
    return f"{expect['tool']}({_fmt(normalise_args(expect['tool'], expect.get('args')))})"


def _fmt(args: dict[str, Any]) -> str:
    return ", ".join(f"{k}={'null' if v is None else str(v).lower()}" for k, v in args.items())


def is_clarifying(turn: Turn) -> bool:
    return not turn.tool_calls and "?" in turn.spoken and bool(CLARIFY.search(turn.spoken))


def matches(expect: dict[str, Any], turn: Turn) -> bool:
    if expect.get("clarify"):
        return is_clarifying(turn)
    if expect.get("tool") is None:
        return not turn.tool_calls
    if not turn.tool_calls:
        return False
    first = turn.tool_calls[0]
    want = normalise_args(expect["tool"], expect.get("args"))
    got = normalise_args(first.name, first.args)
    return first.name == expect["tool"] and all(got.get(k) == v for k, v in want.items())


def chosen(turn: Turn) -> str:
    if not turn.tool_calls:
        return "clarify" if is_clarifying(turn) else "no tool"
    return "; ".join(f"{c.name}({_fmt(normalise_args(c.name, c.args))})" for c in turn.tool_calls)


@dataclass
class Row:
    n: int
    say: str
    expected: str
    got: str
    ok: bool
    tags: list[str]


@dataclass
class CorpusReport:
    rows: list[Row]
    model_id: str | None
    threshold: float

    @property
    def passed(self) -> int:
        return sum(r.ok for r in self.rows)

    @property
    def rate(self) -> float:
        return self.passed / len(self.rows) if self.rows else 0.0

    @property
    def ok(self) -> bool:
        return self.rate >= self.threshold

    def markdown(self) -> str:
        lines = [
            "# Corpus — tool selection from Tower's descriptions",
            "",
            "Generated by `make corpus` (`ref-client corpus`, `services/ref-client/corpus/phrasings.yaml`). The model",
            "chooses from the descriptions Tower advertises (01 §2, verbatim); misses are description bugs.",
            "",
            f"- model: `{self.model_id}`",
            f"- result: **{self.passed}/{len(self.rows)} = {self.rate:.0%}** "
            f"(gate {self.threshold:.0%}: {'pass' if self.ok else 'FAIL'})",
            "",
            "| # | say | expected | chosen | pass |",
            "|---:|---|---|---|---|",
        ]
        for r in self.rows:
            lines.append(f"| {r.n} | {r.say} | {r.expected} | {r.got} | {'✅' if r.ok else '❌'} |")
        misses = [r for r in self.rows if not r.ok]
        if misses:
            lines += ["", "## Misses (fix the description, not the corpus)", ""]
            lines += [f"- #{r.n} “{r.say}” → {r.got} (expected {r.expected})" for r in misses]
        return str(redact("\n".join(lines) + "\n"))


async def run_corpus(
    agent: Agent,
    entries: list[dict[str, Any]] | None = None,
    *,
    threshold: float | None = None,
    echo: Callable[[str], None] | None = None,
) -> CorpusReport:
    rows = []
    for i, entry in enumerate(entries if entries is not None else load_corpus(), start=1):
        turn = await agent.ask(entry["say"])
        exps = expectations(entry)
        ok = any(matches(e, turn) for e in exps)
        row = Row(
            i, entry["say"], " or ".join(describe(e) for e in exps), chosen(turn), ok, entry.get("tags", [])
        )
        rows.append(row)
        if echo:
            echo(f"| {row.n} | {row.say} | {row.expected} | {row.got} | {'✅' if ok else '❌'} |")
    return CorpusReport(rows, agent.model_id, min_pass() if threshold is None else threshold)
