#!/usr/bin/env python3
"""Turn Terraform outputs into deploy/.env.<env>, the endpoints `make demo ENV=…` and `make test-e2e ENV=…` use
(mk/vars.mk includes the file for non-local ENVs). Make-compatible `KEY=value` lines, no secrets: the bearer and
session secrets stay in Terraform state.

    uv run python scripts/render_env.py --env aws      # from artifacts/tf-outputs.json (make outputs)
    uv run python scripts/render_env.py --env eks      # from artifacts/tf-outputs-eks.json (prompt 14)

For eks the mapping covers the keys both stacks share; prompt 14 adds its own.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _tf_outputs import ROOT, load_outputs  # noqa: E402


def aws_env(o: dict[str, Any]) -> dict[str, str]:
    return {
        "TOWER_ENV": "aws",
        "TOWER_URL": str(o.get("tower_mcp_url", "")),
        "BINDING_URL": str(o.get("binding_url", "")),
        "ALERTS_URL": str(o.get("hooks_base_url", "")),
        "MOCK_URL": "",  # internal ALB: reached by Gateway only; the seed uses ECS Exec
        "DYNAMO_ENDPOINT": "",  # real DynamoDB
        "AWS_REGION": str(o.get("region", "")),
        "TOWER_TABLE_PREFIX": str(o.get("table_prefix", "")),
        "TOWER_KMS_KEY_ID": str(o.get("kms_key_arn", "")),
        "TOWER_KMS_HMAC_KEY_ID": str(o.get("kms_hmac_key_arn", "")),
        "CARRIER_CLIENT": "gateway",
        "CARRIER_BACKEND": str(o.get("carrier_backend", "")),
        "CARRIER_BASE_URL": str(o.get("carrier_base_url", "")),
        "CARRIER_GATEWAY_URL": str(o.get("gateway_url", "")),
        "CARRIER_GATEWAY_AUTH": "sigv4",
        "CARRIER_GATEWAY_TOOLS": str(ROOT / "artifacts" / "gateway-tools.json"),
        "MOCK_CLUSTER": str(o.get("mock_cluster_name", "")),
        "MOCK_SERVICE": str(o.get("mock_service_name", "")),
        "MOCK_CONTAINER": str(o.get("mock_container_name", "")),
    }


def eks_env(o: dict[str, Any]) -> dict[str, str]:
    env = {k: v for k, v in aws_env(o).items() if v}
    env["TOWER_ENV"] = "aws"  # same tables and keys as the AgentCore stack (10 §6)
    for key, out in (("TOWER_URL", "tower_url"), ("BINDING_URL", "binding_url"), ("MOCK_URL", "mock_url")):
        if o.get(out):
            env[key] = str(o[out])
    return env


def render(values: dict[str, str]) -> str:
    lines = ["# generated by scripts/render_env.py from terraform outputs — do not edit, do not commit"]
    for k, v in values.items():
        if "\n" in v or "#" in v or "$" in v:
            raise SystemExit(f"{k}: value not representable in a Makefile include")
        lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--env", choices=["aws", "eks"], required=True)
    ap.add_argument("--outputs", type=Path, default=None, help="terraform output -json file")
    ap.add_argument("--out", type=Path, default=None, help="default deploy/.env.<env>")
    args = ap.parse_args(argv)
    outputs = load_outputs(args.outputs, env=args.env)
    values = aws_env(outputs) if args.env == "aws" else eks_env(outputs)
    out = args.out or ROOT / "deploy" / f".env.{args.env}"
    out.write_text(render(values), "utf-8")
    print(f"wrote {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out}")
    for k in ("TOWER_URL", "BINDING_URL", "ALERTS_URL", "CARRIER_GATEWAY_URL"):
        if values.get(k):
            print(f"  {k}={values[k]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
