#!/usr/bin/env python3
"""Grep artifacts/, docs/ and deploy/ for AWS key ids, bearer tokens and E.164 numbers (pre-submission gate).

Two narrow exclusions for phone-number-shaped strings, so the gate stays quiet on things that cannot be numbers:

- epoch-second timestamps in JSON (`"ts":1791321062.27`, `"ttl":1798567200`): 10 digits in the 2017-2039 range,
  either a float or the value of a timestamp key;
- in `docs/` only, the NANP range reserved for fiction (`+1 NXX 555-0100..0199`) — the demo numbers quoted in
  the build log. Under `artifacts/` and `deploy/` (generated output, compose logs) those still fail: a demo number
  there is the privacy leak the gate exists to catch.

`artifacts/sbom/` and `artifacts/scan/` (third-party package inventories) get the key/token checks only.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tests.privacy.patterns import AWS_KEY_ID, BEARER, E164_STRICT, phone_hits  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DIRS = ["artifacts", "docs", "deploy", "scenarios"]
EXT = {".md", ".json", ".txt", ".yaml", ".yml", ".tf", ".tfvars", ".env", ".html", ".log"}
ALLOW_PHONES = {
    "scenarios",
    "docs/architecture",
    "docs/pitch",
    "docs/review",
    "docs/prior-art",
    "prompts",
    "deck",
    "Decks",
}
# Third-party inventories generated by `make sbom` / `make scan` (package ids, SHA hashes, versions): no data of
# ours can reach them, and their hex digests are full of digit runs. Still checked for AWS keys and bearer tokens.
NO_PHONE_CHECK = ("artifacts/sbom/", "artifacts/scan/")
FICTIONAL_NANP = re.compile(r"\+?1\d{3}55501\d{2}")
EPOCH_KEY = re.compile(r'"(?:ts|ttl|exp|iat|nbf|expires_at|created_at)"\s*:\s*$')


def _excused(text: str, m: re.Match[str], in_docs: bool) -> bool:
    s = m.group(0)
    if in_docs and FICTIONAL_NANP.fullmatch(s):
        return True
    if len(s) == 10 and 1_500_000_000 <= int(s) < 2_200_000_000:
        before, after = text[max(0, m.start() - 24) : m.start()], text[m.end() : m.end() + 2]
        return bool(EPOCH_KEY.search(before)) or re.match(r"\.\d", after) is not None
    return False


def phones(text: str, rel: str) -> list[str]:
    """`phone_hits` (the shared privacy rule) minus the two exclusions above."""
    hits = set(phone_hits(text))
    if rel.startswith(NO_PHONE_CHECK):
        return []
    in_docs = rel.startswith("docs/")
    return [
        m.group(0)
        for m in E164_STRICT.finditer(text)
        if m.group(0) in hits and not _excused(text, m, in_docs)
    ]


def main() -> int:
    bad = []
    for d in DIRS:
        for f in (ROOT / d).rglob("*"):
            if not f.is_file() or f.suffix not in EXT or ".terraform" in f.parts:
                continue
            t = f.read_text(errors="ignore")
            rel = f.relative_to(ROOT).as_posix()
            if AWS_KEY_ID.search(t):
                bad.append(f"{rel}: AWS key id")
            if BEARER.search(t):
                bad.append(f"{rel}: bearer token")
            if not any(a in rel for a in ALLOW_PHONES) and phones(t, rel):
                bad.append(f"{rel}: phone-number-shaped string")
    if bad:
        print("secrets/privacy grep found:")
        print("\n".join("  " + b for b in bad))
        return 1
    print("secrets grep: clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
